<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>QuickCrossbowReload</RootNamespace>
    <AssemblyName>QuickCrossbowReload</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>Lib\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="HarmonyLib">
      <HintPath>Lib\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Lib\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Lib\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>Lib\assembly_valheim.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
